version: "3"

services:
    php:
        build: ./docker/php
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:1.19.3
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    db:
        image: postgres:13.0
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - TZ=Asia/Tokyo

volumes:
    postgres-data:
