version: "3"

services:
    php:
        build: ./docker/php
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:1.19.3
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
